services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  vitest:
    build: ./backend
    volumes:
      - ./backend:/server
    command: ["npm", "run", "test"]