# POST http://localhost:4000/user HTTP/1.1
# Content-Type: application/json

# {
#     "name":"Jorge", 
#     "email":"test", 
#     "registration":"test", 
#     "password":"test"
# }


POST http://localhost:4000/auth/user HTTP/1.1
Content-Type: application/json

{
    "registration":"test", 
    "password":"test"
}